partiql/partiql-tests

partiql-test-data/fail/parser/select/select-from-where.ion
partiql-test-data/pass/parser/primitives/literal.ion
partiql-test-data/pass/parser/select/select-from-where.ion
partiql-tests-schema-proposal.md

Resolves #4.
Remodels the `assert` field of the test to be either a struct or list of structs. This provides additional functionality for future tests and tested properties. I included some example test files that have `assert` as a struct and some as a list of structs.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

Update `assert` schema and associated tests, fix typos

---

partiql-test-data/fail/parser/select/select-from-where.ion
partiql-test-data/pass/parser/primitives/aggregate-function-call.ion
partiql-test-data/pass/parser/primitives/call.ion
partiql-test-data/pass/parser/primitives/case.ion
partiql-test-data/pass/parser/primitives/cast.ion
partiql-test-data/pass/parser/primitives/container-constructors.ion
partiql-test-data/pass/parser/primitives/extract.ion
partiql-test-data/pass/parser/primitives/identifiers.ion
partiql-test-data/pass/parser/primitives/operators/at-operator.ion
partiql-test-data/pass/parser/primitives/operators/between-operator.ion
partiql-test-data/pass/parser/primitives/operators/in-operator.ion
partiql-test-data/pass/parser/primitives/operators/is-operator.ion
partiql-test-data/pass/parser/primitives/operators/like-operator.ion
partiql-test-data/pass/parser/primitives/operators/unary-operators.ion
partiql-test-data/pass/parser/primitives/parameter.ion
partiql-test-data/pass/parser/primitives/path-expression.ion
partiql-test-data/pass/parser/primitives/union-except-intersect.ion
partiql-test-data/pass/parser/query/pivot.ion
partiql-test-data/pass/parser/query/select/group-by.ion
partiql-test-data/pass/parser/query/select/having.ion
partiql-test-data/pass/parser/query/select/joins.ion
partiql-test-data/pass/parser/query/select/limit-offset.ion
partiql-test-data/pass/parser/query/select/order-by.ion
partiql-test-data/pass/parser/query/select/select-value.ion
partiql-test-data/pass/parser/query/select/select.ion
partiql-test-data/pass/parser/query/select/set-quantifier.ion
partiql-test-data/pass/parser/query/select/unpivot.ion
partiql-test-data/pass/parser/select/select-from-where.ion

Part of #5.
Adds tests from the latest commit of [SqlParserTests.kt](https://github.com/partiql/partiql-lang-kotlin/blob/34625c68dbcbaf7b8ae60df7a4cf65c60b2a3b79/lang/test/org/partiql/lang/syntax/SqlParserTest.kt). `SqlParserTests.kt` is one of the larger files with parser tests. Omits some tests that are not part of the current spec (e.g. DML, DDL, `LET` clause) along with some other tests (full details in this [issue comment](https://github.com/partiql/partiql-lang-kotlin/blob/34625c68dbcbaf7b8ae60df7a4cf65c60b2a3b79/lang/test/org/partiql/lang/syntax/SqlParserTest.kt)).
Also, fixes an error in the parse error assertion result. `ParserError` -> `ParseError`.
I verified the new test files are parseable using the Rust test runner created in …

Add spec-defined SqlParserTest tests; fix ParseError symbol

---

partiql-lang-kotlin-omitted-tests.md
partiql-test-data/fail/parser/primitives/date-constructor.ion
partiql-test-data/fail/parser/primitives/time-constructor.ion
partiql-test-data/fail/semantic/primitives/date-constructor.ion
partiql-test-data/fail/semantic/primitives/time-constructor.ion
partiql-test-data/pass/parser/primitives/date-constructor.ion
partiql-test-data/pass/parser/primitives/time-constructor.ion

Finishes off the Kotlin parsing test issue https://github.com/partiql/partiql-tests/issues/5.
Ports tests from `DATE` and `TIME` constructors tests from [SqlParserDateTimeTests.kt](https://github.com/partiql/partiql-lang-kotlin/blob/34625c68dbcbaf7b8ae60df7a4cf65c60b2a3b79/lang/test/org/partiql/lang/syntax/SqlParserDateTimeTests.kt) and [ParserErrorsTest.kt](https://github.com/partiql/partiql-lang-kotlin/blob/34625c68dbcbaf7b8ae60df7a4cf65c60b2a3b79/lang/test/org/partiql/lang/errors/ParserErrorsTest.kt#L2848-L3099).
Verified these could be properly parsed by the Rust conformance test runner. As of https://github.com/partiql/partiql-lang-rust/commit/f57ee41e49c6d00027114bffe6f349dbe699dff3, the conformance test output is:
```
333 passed; 50 failed; 56 ignored; 0 measured; 0 filtered out; …
```

Port DATE and TIME parse tests from Kotlin implementation

---

README.md
docs/partiql-tests-schema-proposal.md
partiql-tests-data/fail/eval/query/select/select.ion
partiql-tests-data/partiql-tests-schema.isl
partiql-tests-data/success/eval-equiv/README.md
partiql-tests-data/success/eval-equiv/path.ion
partiql-tests-data/success/eval/query/select/select.ion
partiql-tests-validator/src/test/kotlin/org/partiql/tests/validator/PartiQLTestDataValidator.kt

Issue #, if available: #17 and #20
Adds evaluation and equivalence schema proposal and ISL definitions. Additionally, makes some other changes:
- adds some example `EvaluationSuccess`, `EvaluationFail`, and equivalence tests
- changes structs to be closed content, which can help prevent using the wrong assertion fields (e.g. including an `output` for an `EvaluationFail` `result`)
- ISL validation tests related to evaluation + equivalence

Add evaluation and equivalence conformance test schema

---

docs/partiql-tests-schema-proposal.md
partiql-tests-data/fail/eval/query/select/select.ion
partiql-tests-data/partiql-tests-schema.isl
partiql-tests-data/success/eval-equiv/path.ion
partiql-tests-data/success/eval/query/select/select.ion
partiql-tests-validator/src/test/kotlin/org/partiql/tests/validator/PartiQLTestDataValidator.kt

Issue #, if available: #25
Adds the `EvalMode` option to the evaluation test schema to represent the different dynamic type mismatch behaviors specified in the PartiQL specification (see [section 4.1](https://partiql.org/assets/PartiQL-Specification.pdf#subsection.4.1)).

Add `EvalMode` to evaluation test assertion

---

partiql-tests-data/eval/spec-tests.ion

From some offline discussions, there's some confusion (and possibly incorrect `partiql-lang-kotlin` behavior) related to `SELECT *` when a `FROM` source is aliased.
```
PartiQL> SELECT * FROM someOrderedTable[0].a AS x
|
==='
<<
{
'_1': 0
}
>>
---
OK!
```
while the following outputs something differently
```
PartiQL> SELECT * FROM <<{'x':0}>>
|
==='
<<
{
'x': 0
}
>>
```
The `FROM` source of both queries should be outputting the same binding tuple (i.e. `<< < x : 0 > >>`) but the result differs. I tried to find further explanation of `SELECT *`'s behavior in the spec, but couldn't find much other than what's mentioned in section [6.3.2](https://partiql.org/assets/PartiQL-Specification.pdf#subsubsection.6.3.2) related to `SELECT x.*`. The modified tests relate to [section …

Adjusts the section 5 spec tests to not use `SELECT *`

---

partiql-tests-data/eval/primitives/operators/case-operator.ion

Original ported tests from [EvaluatorTestSuite.kt](https://github.com/partiql/partiql-lang-kotlin/blob/main/lang/src/test/kotlin/org/partiql/lang/eval/EvaluatorTestSuite.kt#L753-L787) had a redundant `WHEN` branch that repeated `WHEN NULL THEN`.

Update case op tests

---

partiql-tests-data/eval/primitives/functions/position.ion

`POSITION` outputs numbers, not strings

---

partiql-tests-data/eval/primitives/functions/nullif.ion

Existing test case result was wrong. `NULLIF(MISSING, MISSING)` should result in `MISSING` and not `NULL`. 
If we reduce `NULLIF` to a `CASE WHEN` expression as specified in the [SQL-92 spec section 6.9 page 141](http://www.contrib.andrew.cmu.edu/~shadow/sql/sql1992.txt), `NULLIF(MISSING, MISSING)` is equivalent to:
```
CASE WHEN MISSING = MISSING THEN NULL ELSE MISSING END
```
Since `MISSING = MISSING` is not true, the result is the else branch, `MISSING`.

Fix `NULLLIF(MISSING, MISSING)` test case

---

partiql-tests-data/eval/primitives/operators/like.ion

Adds more tests for `LIKE` dealing with:
- non-literal arguments
- NULL + MISSING propagation
- mistyped arguments
Unknown propagation rules follow from section [8.5 of the SQL-92 spec](http://www.contrib.andrew.cmu.edu/~shadow/sql/sql1992.txt):
```
1) If an <escape character> is specified and M, P, or E is the null
value, then
M LIKE P ESCAPE E
is unknown.
2) If an <escape character> is not specified and M or P is the null
value, then
M LIKE P
is unknown.
```
NULL/MISSING and mistyped arguments follow [section 7 of the PartiQL spec](https://partiql.org/assets/PartiQL-Specification.pdf#section.7).

Add more LIKE tests (null, missing, mistyped, variable type args)

---

partiql-tests-data/eval/primitives/operators/like.ion

Some empty, inline comments were added in https://github.com/partiql/partiql-tests/pull/49, which caused some parsing errors with `ion-rs` ([example failing build](https://github.com/partiql/partiql-lang-rust/actions/runs/4048525189/jobs/6963874842)). I believe it's a bug in `ion-rs` (still confirming) as it parses fine with IonJava and isn't forbidden in the Ion spec. In the meantime, just removing those empty, inline comments to let `partiql-lang-rust` use the latest version of `partiql-tests`. 

Remove empty inline comments

---

.github/workflows/build.yml
partiql-tests-data/success/syntax/query/select/joins.ion

Removes some `OUTER JOIN` tests that don't include an outer join type (i.e. `LEFT`, `RIGHT`, `FULL`). From [Josh's comment](https://github.com/partiql/partiql-lang-rust/pull/306#issuecomment-1435244301) in a recent Rust PR:
```
Tests are here: 
https://github.com/partiql/partiql-tests/blob/main/partiql-tests-data/success/syntax/query/select/joins.ion#L105-L118
- 
SELECT x FROM a, b CROSS JOIN c LEFT JOIN d ON e RIGHT OUTER CROSS JOIN f OUTER JOIN g ON h
- 
SELECT x FROM a INNER CROSS JOIN b CROSS JOIN c LEFT JOIN d ON e RIGHT OUTER CROSS JOIN f OUTER JOIN g ON h
They both presume that `<x> OUTER JOIN <y>` is equivalent to `<x> FULL OUTER JOIN <y>`, but I have found:
-  no SQL database that supports this,
- the [SQL syntax](https://jakewheat.github.io/sql-overview/sql-2016-foundation-gramma …
```

Add outer join type to `OUTER JOIN`

---

partiql-tests-data/eval/query/group-by/group-by.ion

Addresses https://github.com/partiql/partiql-tests/issues/59.
Ports more `GROUP BY` tests from partiql-lang-kotlin which were not part of the previously ported tests. This PR (in its current state) ports most of the tests from `EvaluatingCompilerGroupByTest.kt`. There still remains some tests that haven't been ported (see [EvaluatingCompilerGroupByTest.kt#L1195-L1400](https://github.com/partiql/partiql-lang-kotlin/blob/main/lang/src/test/kotlin/org/partiql/lang/eval/EvaluatingCompilerGroupByTest.kt#L1195-L1400)).
Putting this out as I'll be away for at least a couple weeks.

Port more `GROUP BY` tests from partiql-lang-kotlin

---

partiql-tests-data-extended/eval/query/group-by/group-by.ion
partiql-tests-data/eval/query/group-by/group-by.ion

Due to ambiguity of the PartiQL and SQL92 specs' support of `SELECT *` with `GROUP BY`, replaced the `SELECT * ... GROUP BY ...` tests with column references. Tracking spec issue: https://github.com/partiql/partiql-spec/issues/48. Moved the `SELECT * ... GROUP BY ...` tests to the `extended/` folder.
Also deleted some `GROUP BY` tests that were repeated through the porting process from `partiql-lang-kotlin`.

Replace `SELECT *` with `GROUP BY` tests with column references; delete duplicate tests

---

partiql-tests-data/eval/query/group-by/group-by.ion

Addresses #73.
`partiql-lang-kotlin` and tests ported from `partiql-lang-kotlin` to `partiql-tests` had the incorrect behavior when a group key value was `MISSING`. `MISSING` should be coerced to `NULL` as per [section 11.1.1](https://partiql.org/assets/PartiQL-Specification.pdf#subsubsection.11.1.1) of the PartiQL spec. Previously, the group key would be `MISSING` in the edge case of when no other group keys values were `NULL`.

Fix `GROUP BY` tests grouping over `MISSING`

---

partiql-tests-data/eval/primitives/functions/extract.ion

Related to first part of #83.
Adjusts the `EXTRACT` builtin function tests to assert on the expected result in the PartiQL statement. This is to deal with the SQL specification's ambiguity related to the output type of `EXTRACT`. In SQL:2011 (pg 1337):
```
The declared type of <extract expression> is an implementation-defined exact numeric type. If <primary
datetime field> specifies SECOND, then the scale is implementation-defined; otherwise, the scale is
0 (zero).
```
where "exact numeric type" refers to "NUMERIC, DECIMAL, SMALLINT, INTEGER, and BIGINT" (pg 15).
Rather than defining the exact numeric type output by `EXTRACT` to be a decimal or integer, we add a PartiQL equality expression to assert the equivalent value.
E.g. rewrite
```
{
...
statement:"EXTRACT(YEAR FROM DATE …
```

Adjusts `EXTRACT` tests to assert on result in statement

---

partiql-tests-data/eval/primitives/functions/extract.ion

Timezone was omitted from a `TIME WITH TIME ZONE` literal value in a test.

Fix omitted time zone from extract test case

---

partiql-tests-data-extended/eval/primitives/functions/text_replace.ion

Closes #78.
Ports the `text_replace` tests to `partiql-tests`. Also adds null/missing propagation tests and mistyped argument tests.
These tests are ported under the "extended" directory because the name isn't part of any SQL spec I could find. It appears most other SQL databases (e.g. postgresql, mysql, sqlite, oracle) use the name `REPLACE`.

Ports `text_replace` tests to `partiql-tests` and adds null/missing/mistyped argument tests

---

partiql-tests-data/eval/primitives/coll-aggregate-function.ion

Fixes a few `COLL_` tests:
- `COLL_COUNT` tests returned null rather than 0 when the collection contained `missing`
- A couple `COLL_ANY` and `COLL_SOME` tests had an extra right bracket

Fix a few `COLL_` test typos

---

docs/partiql-tests-schema-proposal.md
partiql-tests-data/eval/experimental/graph/directionality.ion
partiql-tests-data/eval/experimental/graph/small_graphs.ion

These conformance tests are ported from some of the unit tests in EvaluatingCompilerGraphMatchTests in partiql-lang-kotlin, https://github.com/partiql/partiql-lang-kotlin/pull/1104
Adjustments to reading-in Ion made in #1104 are necessary for reading in and running these new conformance tests here. 

Start on conformance tests for graph query.

---

partiql-tests-data/eval/rfc/0007.ion

With partiql-lang-kotlin, 2 of them now succeed and the other fails for a better reason.
These fixes stem from exploring the purported conformance regression in https://github.com/partiql/partiql-lang-kotlin/pull/1104. 
(The proximate cause of (wrongly) detecting the regression there was probably that `0007.ion` contained two different tests under the same name.)

Fixes to 3 tests in 0007.ion

---

partiql-tests-data/eval/primitives/operators/bag-operators.ion

Fixes #97. Following the bag operator RFC fixes/corrections as part of https://github.com/partiql/partiql-docs/pull/44, fixes the `UNION` ALL tests that include duplicate elements.
For context, these tests were previously ported from the Kotlin implementation. Those tests in the Kotlin codebase should be fixed as part of https://github.com/partiql/partiql-lang-kotlin/issues/1132.

Fix bag op UNION ALL tests

---

partiql-tests-data/eval/primitives/operators/bag-operators.ion
partiql-tests-data/success/syntax/primitives/union-except-intersect.ion

Adds some more syntax and evaluation tests with the bag operators. These tests focus on using the bag operators with `ORDER BY`, `LIMIT,` and `OFFSET`.

Add some more bag op tests with ORDER BY LIMIT OFFSET

---

partiql-tests-data/eval/primitives/operators/bag-operators.ion

Adds an outer intersect test with the RHS containing elements that aren't on the LHS.

Add another outer intersect test

---

partiql-tests-data/eval/primitives/functions/mod.ion

Fixes some `MOD` function data type mismatch tests. Tests should have returned `MISSING` in permissive/coerce typing mode and errored in strict/error typing mode.

Fix MOD function data type mismatch tests

---

partiql-tests-data/eval/query/order-by.ion

Ported test from https://github.com/partiql/partiql-tests/pull/66 had the wrong struct field name in statement and expected output (test source: https://github.com/partiql/partiql-lang-kotlin/blob/main/partiql-lang/src/test/kotlin/org/partiql/lang/eval/EvaluatingCompilerOrderByTests.kt#L193-L197).

Fix ORDER BY test typos

---

partiql-tests-data/eval/query/order-by.ion

Adds a couple tests that weren't part of original ORDER BY tests. These tests use `DESC` for the order by expr along with the `NULLS FIRST` and `NULLS LAST` modifiers.

Add a couple more ORDER BY tests using DESC

---

partiql-tests-data/eval/query/group-by/group-by.ion
partiql-tests-data/fail/static-analysis/query/select/having.ion

There was a test (`SELECT rep, SUM(total_sales) as total FROM sales_report HAVING rep = \"Meg\"`) that was previously classified as an evaluation fail. Should be classified as a static analysis fail.

Change classification of a HAVING test

---

partiql-tests-data/eval/primitives/operators/nary-operators.ion

Adds more list, bag, and tuple equality tests based on equality definition specified in [section 7.1.1](https://partiql.org/assets/PartiQL-Specification.pdf#subsubsection.7.1.1) of the spec.
All currently passing w/ the Kotlin implementation.

Add more list, bag, and tuple equality tests

---

partiql-tests-data/eval/query/order-by.ion

- None
- Fixes formatting of data, causing issues in experimental evaluator
- Quantitative impact:
- For new evaluator, "Number passing in legacy engine but fail in eval engine: " **760 --> 692**
- This translates to a conformance increase: **82.40% --> 83.57%**
- Old evaluator stays the same in conformance. Passing 5382 tests.

Fixes formatting of data, causing issues in experimental evaluator

---

partiql-tests-data/eval/misc.ion
partiql-tests-data/eval/primitives/date-time.ion
partiql-tests-data/eval/primitives/operators/bag-operators.ion
partiql-tests-data/eval/query/group-by/group-by.ion
partiql-tests-data/eval/query/select/from-clause.ion
partiql-tests-data/eval/query/select/projection.ion
partiql-tests-data/eval/query/select/select.ion
partiql-tests-data/eval/query/select/sql-aggregate.ion
partiql-tests-data/eval/query/undefined-variable-behavior.ion
partiql-tests-data/eval/spec-tests.ion

- Corrects 80+ incorrect tests.
- The following sections break down each test and why they're wrong according to the PartiQL Specification.
The excerpt below comes from the PartiQL Specification and states that, in strict mode, the query will FAIL when the RHS of a FROM is a scalar. In permissive, it'll be coerced to a bag holding the scalar.
> In the following cases the expression in the FROM clause item has the wrong type. Under the type checking option, all of these cases raise an error and the query fails. Under the permissive option, the cases proceed as follows:
>
> Iteration over a scalar value: Consider the query:
> FROM s AS v AT p
> or the query:
> FROM s AS v
>
> where s is a scalar value. Then s coerces into the bag \<\< s \>\>, i.e., the bag that has a single element, the s. …

Corrects tests regarding coercion, indexing, bag operators, and missing attributes

---

partiql-tests-data/eval/primitives/operators/is-operators.ion
partiql-tests-data/fail/static-analysis/primitives/cast.ion

Issue #71 
- Add `IS` operator test for decimal type. 
- Add invalid decimal type parameter to `fail/staticAnalysis`

Adds tests for checking DECIMAL types

---

partiql-tests-data/eval/primitives/operators/case-operator.ion

- Corrects case-when conformance tests
- Notice that all tests affected evaluate `missing + 1`, which in strict mode should fail execution.

Corrects case-when conformance tests

---

partiql-tests-data/eval/primitives/path.ion

- Fixes several path tests according to the PartiQL Specification
Note: Please click "Hide Whitespace" on the Files Changed tab. The file was formatted oddly, so I allowed my IDE to auto-format.

Fixes several path tests according to the PartiQL Specification

---

partiql-tests-data/eval/primitives/cast.ion

Fixes cast conformance tests.
- We have decided that `NULL` and `MISSING` aren't types. They are values that may fit into the domains of all other types.
- Instead of `CAST(<expr> AS NULL)`, one should just use `NULL`. Same goes for `MISSING`.
- Fixes the `CAST(<expr> AS INT)` tests.
- `INT` corresponds with a 4-byte integer (range of: -2147483648 to 2147483647)
- `BIGINT` corresponds with an 8-byte integer (range of: -9223372036854775808 to 9223372036854775807)
- The old tests cast BIGINT values to INT (causing failures). These tests are wrong, and I've updated them to reflect the expected behavior.

Fixes cast conformance tests

---

partiql-tests-data/eval/primitives/operators/bag-operators.ion
partiql-tests-data/eval/rfc/0007.ion
partiql-tests-data/success/syntax/primitives/union-except-intersect.ion

- Related to https://github.com/partiql/partiql-lang/issues/76 and https://github.com/partiql/partiql-tests/pull/120
- Same tests changed as https://github.com/partiql/partiql-tests/pull/122
- Fixes some more PartiQL bag op tests related to https://github.com/partiql/partiql-tests/pull/120. Specifically for strict mode, error when an outer bag op argument is a non-collection
- Also adds some PartiQL bag op parsing tests using `ORDER BY`, `LIMIT`, and `OFFSET`

Fix some more SQL set op + PartiQL bag op tests

---

partiql-tests-data/eval/query/join/joins.ion
partiql-tests-data/eval/query/select/select.ion

Picked out the relevant ones from #122. See the description there.

Fixes join test cases

---

partiql-tests-data/eval/query/pivot.ion
partiql-tests-data/eval/query/select/projection.ion

Other small fixes that are relatively straightforward.

Fixes miscellaneous test cases

---

partiql-tests-data/eval/query/group-by/group-by.ion
partiql-tests-data/eval/query/select/select-mysql.ion
partiql-tests-data/eval/query/undefined-variable-behavior.ion

Picked out the relevant ones from #122. See the description there.

Fixes undefined variable behavior tests

---

partiql-tests-data/eval/primitives/naughty-strings.ion
partiql-tests-data/eval/primitives/string.ion

A handful of tests used quoted ion symbols as keys in structs, rather than strings. This seems to be a typo that happens to work as the ion is coerced into text.
These were originally ported from an old version of the PartiQL-Lang-Kotlin test scripts: https://github.com/partiql/partiql-lang-kotlin/blob/v0.7.0-alpha/testscript/pts/test-scripts/primitive-types/naughty-strings.sqlts#L20
This PR changes the keys to strings.
E.g., 
```{ `key`:  'value' }``` -> ```{ 'key': 'value'}```
---

Change struct keys from ion to strings for string tests

---

partiql-tests-data/eval/primitives/operators/case-operator.ion

None.
This reverts commit 5aca10abe04039d70d69e94db233e848884d5656 from #115. Behavior is missing literals should behave as null literals and not error in strict mode. See this summary of discussion from a prior PR -- https://github.com/partiql/partiql-tests/pull/118#issuecomment-2248990609.

Revert "Corrects case-when conformance tests"

---

partiql-tests-data/eval/experimental/graph/small_graphs.ion

Gives some graph tests better names.
Due to the way that partiql-lang-rust conformance tests were generated, some of the graph tests conflicted with one another when only punctuation was different.
---

Better graph test names

---

partiql-tests-data/eval/ion/primitives/null.ion
partiql-tests-data/eval/ion/primitives/operators/nary-operators.ion
partiql-tests-data/eval/ion/primitives/symbol.ion
partiql-tests-data/eval/ion/query/order-by.ion
partiql-tests-data/eval/ion/query/select/from-clause.ion
partiql-tests-data/eval/ion/query/select/projection.ion

Updates the ion tests for boxed variant/ion data encoding changes.
---

Update ion tests for boxed variant/ion changes.

---

partiql-tests-data/eval/experimental/graph/gpml-paper.ion

Follow-on to https://github.com/partiql/partiql-tests/pull/139
Also adds some nesting to test structure.
Tests in sections `labels` and `where` are unchanged.
3-hop tests have been refactored into equivalence class tests.
4- and 6-hop tests have been added.
---

Add more multi-hop mode tests; Refactor graph test structure

---

partiql-tests-data/eval/primitives/operators/between-operator.ion

None
Add more `BETWEEN` operator tests between numeric types.

add: BETWEEN tests with numeric types

---

partiql-tests-data/eval/query/setop.ion

Additional tests with limit, offset, and order by applied on the set operators (UNION, INTERSECT, EXCEPT).

add: tests with limit, offset, and order by on set ops

---

partiql-tests-data/eval/primitives/logical.ion

Prior PR that added more logical operator tests included a test with the wrong behavior for `NOT MISSING`. It should return `NOT NULL`.

fix: NOT MISSING test

---

partiql-tests-data/eval/ion/primitives/null.ion
partiql-tests-data/eval/primitives/null.ion

In prior tests including `missing` as an operand on `=` operator, `missing` was returned mistakenly. Fix these tests in this PR.

fix: null tests including missing

---

docs/partiql-tests-schema-proposal.md
partiql-tests-data/eval/primitives/cast.ion
partiql-tests-data/eval/primitives/functions/abs.ion
partiql-tests-data/eval/primitives/interval.ion
partiql-tests-data/eval/primitives/operators/divide.ion
partiql-tests-data/eval/primitives/operators/minus.ion
partiql-tests-data/eval/primitives/operators/plus.ion
partiql-tests-data/eval/primitives/operators/times.ion

Close #144 #143 #145 
Port current PLK evaluation unit tests on `INTERVAL` to the conformance tests, including:
- arithmetic operation tests (plus, minus, times, divide)
- abs function tests
Also add some tests on:
- literal tests
- sign parsing tests
- casting tests

add: interval conformance tests

---

partiql-tests-data/eval/query/group-by/group-by.ion

Following https://github.com/partiql/partiql-tests/pull/158, add more tests with explicit/implicit case.

add: more qualified reference tests with case on `GROUP BY`
